### ISSUE TITLE
Thêm comment cho post

### ISSUE THREAD

**Issue by linuxhjkaru** [NishaLab/Simple_Blogpost#10]
Thêm phần comment cho mỗi post.
Design sẽ giống như facebook. Bên dưới post hiển thị các comment cũ và chỗ nhập comment mới + hiển thị reaction.
Em sẽ phải tự tìm hiểu, tách thành các task con.
Đầu tiên là tách thành các task con để a review rồi sẽ làm tiếp

**Comment by NishaLab** [comment]
Ý tưởng:
Coi 1 comment như 1 micropost từ đó có thể tái sự dụng được quan hệ User-React-Micropost
=> 1 Micropost có thể có nhiều Micropost con => sinh thêm thuộc tính parent_id trong lớp Micropost => nếu là post cha thì thuộc tính này sẽ là null
![image](https://user-images.githubusercontent.com/57358091/95297325-78d7cf00-08a4-11eb-9610-7e6efe8d76ee.png)

Estimate: 6 hours
