### ISSUE TITLE
Thêm reaction cho post

### ISSUE THREAD

**Issue by linuxhjkaru** [NishaLab/Simple_Blogpost#11]
Thêm reaction cho post. Design sẽ như facebook.

**Comment by NishaLab** [comment]
Ý tưởng: mỗi reaction sẽ có thông tin của post và user react post đó -> tạo  model Reaction với attr: id, user_id, post_id, react_id -> Model giống như quan hệ giữa 3 Object User, Post và ReactIcon
Coi hệ thống chọn reaction giống như hệ thống upload file avatar lên post thay vì người dùng upload file lên thì sẽ hệ thống sẽ có sẵn những ảnh react cho người dùng chọn -> khi người dùng chọn 1 react hệ thống tự tạo ra 1 model Reaction tương ứng
DB:
![image](https://user-images.githubusercontent.com/57358091/94781032-7af8e400-03f3-11eb-8aaf-21c1e2e594a2.png)

Estimate: 6 hours
