### ISSUE TITLE
Auto deploy

### ISSUE THREAD

**Issue by linuxhjkaru** [NishaLab/Simple_Blogpost#16]
Không biết em đã nghe nói về CI/CD chưa, nếu chưa thì tìm hiểu nhé.
Task này a muốn em tích hợp CircleCI của Github.
CI sẽ check Rubocop + RSpec.
Nếu pull được merge vào master thì auto deploy lên heroku.

**Comment by NishaLab** [comment]
Estimate: 6 hours
