### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by linuxhjkaru** [NishaLab/Simple_Blogpost#19]
Thông báo cho user mỗi khi có ai đó react hay comment.
Thông báo bao gồm trên màn hình (giống facebook) + gửi email
Việc thông báo phải là real-time, tức là ai có comment gì là phải thông báo ngay, ko cần reload lại trang.
Hiển thị trên màn hình thì tùy em design chỗ hợp lý

**Comment by NishaLab** [comment]
Estimate: 6 hours
