### ISSUE TITLE
Chức năng chat 

### ISSUE THREAD

**Issue by linuxhjkaru** [NishaLab/Simple_Blogpost#26]
Ở màn hình account profile sẽ thêm button "Send Message" (dưới phần hiển thị following, follower)
Khi bấm vào button thì sẽ hiển thị khung chat ở góc dưới bên phải.
2 user có thể chat vs nhau.
Lưu ý: Lưu lại lịch sử chat

**Comment by NishaLab** [comment]
Estimate: 6 hours
Thêm 1 model Message gồm id của 2 user và content gửi
2 user chat với nhau -> sử dụng channel để chat real times
